CREATE TABLE IF NOT EXISTS 'GALLERY_ITEM'
    (_id TEXT PRIMARY KEY UNIQUE,
    title TEXT,
    description TEXT,
    page_views INTEGER,
    url TEXT,
    uploader TEXT,
    upvotes INTEGER,
    downvotes INTEGER,
    score INTEGER,
    is_album INTEGER,
    cover_image_id TEXT,
    album_layout TEXT,
    num_images INTEGER,
    image_mime_type TEXT,
    is_animated INTEGER,
    width INTEGER,
    height INTEGER,
    size_bytes INTEGER,
    bandwidth_bytes INTEGER,
    delete_hash TEXT,
    submission_datetime TEXT,
    first_synced_datetime TEXT,
    last_synced_datetime TEXT);